[project]
name = "ai-research-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.2.18",
    "langchain-openai>=1.2.1",
    "langchain-groq>=0.0.1",
    "python-dotenv>=1.2.2",
    "langchain-community>=0.4.1",
    "duckduckgo-search>=8.1.1",
    "ddgs>=9.14.2",
    "langgraph>=1.1.10",
    "chromadb>=1.5.9",
    "pypdf>=6.11.0",
    "fastapi>=0.136.1",
    "uvicorn>=0.46.0",
]
